Reply to
drkTettnang/corona-testing pull request #3
Opened 2021-04-06 14:24 UTC by schauer

Fixes #2

2021-04-06 14:31 UTC, schauer commented
Ist noch nicht getestet und müsste [gesquashed ](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges)werden.

2021-04-06 18:44 UTC, sualko requested changes
Ich pushe gleich einen Commit der die Funktion nachrüstet. Trotzdem vielen Dank für die Contribution, vor allem da es die erste für dieses Projekt war :tada:

2021-04-06 18:44 UTC, sualko commented on lib/Config.ts
> +    public static readonly REPLY_TO = process.env.SMTP_REPLY_TO || process.env.SMTP_FROM;
`Config` ist gedacht für Einstellungen die sowohl im Browser als auch Server verfügbar sind, daher auch der `NEXT_PUBLIC_` Prefix.

2021-04-06 18:44 UTC, sualko commented on lib/Config.ts
> +    public static readonly REPLY_TO = process.env.SMTP_REPLY_TO || process.env.SMTP_FROM;
Wenn kein replyTo gesetzt ist, sollte dieser Header auch nicht in der Mail auftauchen.

2021-04-06 18:44 UTC, sualko commented on lib/email/cancel.ts
> +        replyTo: Config.REPLY_TO,
Da dieser Header überall genutzt werden soll, wäre das global in `lib/smtp.ts` besser.

2021-04-06 18:50 UTC, closed without merging

2021-04-07 12:15 UTC, schauer commented
Sehr gerne und vielen Dank für das Feature :smiley::thumbsup: